### ISSUE TITLE
Logrus Helper: logrus_mate dependencies problem

### ISSUE THREAD

**Issue by kahlys** [heirko/go-contrib#1]
I think some packages have changed because there is a dependency problem by getting the package logrusHelper.
```
$ go get -u github.com/heirko/go-contrib/logrusHelper
# github.com/heirko/go-contrib/logrusHelper
../github.com/heirko/go-contrib/logrusHelper/config.go:13: undefined: logrus_mate.LoggerConfig
../github.com/heirko/go-contrib/logrusHelper/config.go:25: undefined: logrus_mate.LoggerConfig
```

**Comment by heralight** [comment]
Hi,

logrus_mate have change its api in a v2 version...
Then, I made a fork of it and fix the problem.
I added a unit test.

best regards,

Alexandre Richonnier
