### ISSUE TITLE
Request for adding a new function 

### ISSUE THREAD

**Issue by avinash92c** [heirko/go-contrib#3]
I tried cloning and creating a branch but i do not have privileges. so could you please add the below function to the library under go-contrib\logrusHelper\config.go
it will help if i have my viper configuration categorized and want to load to loggerconfig.

```
// UnmarshalConfigurationByKey read configuration from viper by a category key.
//  e.g., if you have all your logging properties under a common key logging
// It returns a logrus_mate logger configuration instance.
func UnmarshalConfigurationByKey(key string, viper *viper.Viper) (conf mate.LoggerConfig) {
	err := viper.UnmarshalKey(key, &conf)
	if err != nil {
		log.Fatalf("unable to decode into struct, %v", err)
	}
	if err = conf.Validate(); err != nil {
		panic(err)
	}
	return
}
```

**Comment by heralight** [comment]
Hi,

Thank you for your idea, I add to the library, you can find it in master.
About the Pull request problem, normally you can fork this repository, write your modification in your fork, then push a pull request, this is the classic way.

Best regards,

Alexandre
